### ISSUE TITLE
Unable to convert Enterprise Architect generated EMF files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/libemf2svg#1]
SparxSystem's Enterprise Architect software generates EMF files that can be read on Windows (Microsoft Word), but not by libemf2svg. Somehow, libemf2svg crashes/exits on the input of these files.

We have to fix libemf2svg so that it reads these files and successfully converts these EMF files into SVG.

**Comment by ronaldtse** [comment]
From @maxirmx:

1. It looks like the issue is related to 0 size for all text objects A sample record generated to SVG file:
```
<text font-family="Carlito" fill="#000000" style ="white-space:pre;"
font- weight="700" text-anchor="start" x="0.0000" y="0.0000"
font-size="0.0000" ><![CDATA[SF_SamplingSolid]]></text>
```

2. Further research shows that there all font attributes are set to `0` because `viewport viewPortExX` property is always `0`
3. Further `viewport` property is never initialized since there is no `EMR_SETVIEWPORTEXTEX` records in sample EMF files
4. I assume that the root cause of the problem is the wrong default value for `viewPortExX`.

It may the wrong assumption or not the only problem, but this is an issue I am going to investigate first.

**Comment by ronaldtse** [comment]
From @maxirmx :

> IMHO Output of libqemf is shifted because emf file misses some control statements in the beginning.
> 
> As for the code I will set up auto tests today and see what's wrong. It may simple integration issue

**Comment by maxirmx** [comment]
Implemented by sample from libqemf  (https://sourceforge.net/projects/libqemf/)
