### ISSUE TITLE
Ensure libemf2svg works on Windows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/libemf2svg#11]
In the Metanorma project we need to ensure libemf2svg also compiles on Windows.

* Add Windows GHA build
* Update CMake and code if necessary

**Comment by maxirmx** [comment]
We will use argp-standalone port by
https://github.com/bigcat26/argp-standalone

**Comment by maxirmx** [comment]
libemf2svg now supports Windows native build

**Comment by maxirmx** [comment]
Testing was very limited and really covered memory leaks only. That was the limitation of original code.
 I did some manual validation for Windows version but found that libemf2svg uses random number generator to create clip ids in svg files. That means that output changes from run to run and automatic comparison with the previous results is not possible.
