### ISSUE TITLE
Macintosh arm64 architecture not recognised

### ISSUE THREAD

**Issue by opoudjis** [metanorma/libemf2svg#19]
When I try to install this gem under arm64, via gem install emf2svg, I get:

ld: warning: ignoring file /private/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-18736-2tn5lo/libemf2svg/deps/lib/libfmem.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

And indeed, libemf2svg/deps/lib/libfmem.a is compiled as x86_64, not the desired xarm64 architecture

This occurs because deps/src/fm-build/CMakeFiles/fmem.dir/flags.make ends up containing -arch x86_64

And that occurs, because deps/src/fm-build/CMakeFiles/3.22.0/CMakeSystem.cmake contains

set(CMAKE_HOST_SYSTEM_PROCESSOR "x86_64")
set(CMAKE_HOST_SYSTEM_PROCESSOR "x86_64")

instead of the correct xarm64

I can't work out what is going on when I try to build it; I just know that this gem is doing a lot of patching of vcpkg, and vcpkg seems to be the only place where the cmake architecture is manipulated.

**Comment by opoudjis** [comment]
Worse: when I compile this repo on its own, it injects the correct xarm64. 

Only when it compiled in the context of building emf2svg does it fail to detect the correct architecture.

**Comment by opoudjis** [comment]
If I go to the temp directory generated to install libemf2svg during emf2svg-ruby compilation, and run

cmake .
make
make install

then the buildfiles use xarm64

The error message is:

````
/Users/nickn/.rvm/rubies/ruby-3.0.3/bin/ruby -I /Users/nickn/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0 -r ./siteconf20211205-39236-4giipm.rb extconf.rb
Downloading libemf2svg.tar.gz (  0%) 
Extracting libemf2svg.tar.gz into /var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks... DEBUG: env is {}
DEBUG: command is ["bsdtar", "zxf", "/Users/nickn/.rvm/gems/ruby-3.0.3/gems/emf2svg-1.0.0/ports/archives/libemf2svg.tar.gz", "-C", "/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks"]
DEBUG: options are {[:out, :err]=>["/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks/extract.log", "a"]}
OK
DEBUG: env is {}
DEBUG: command is ["cmake", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_INSTALL_PREFIX=/Users/nickn/.rvm/gems/ruby-3.0.3/gems/emf2svg-1.0.0/ext/port", "."]
Running 'configure' for libemf2svg 1.3.0... DEBUG: options are {[:out, :err]=>["/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks/configure.log", "a"]}
OK
DEBUG: env is {}
DEBUG: command is "cmake --build /var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks/libemf2svg --config Release --target emf2svg"
Running 'compile' for libemf2svg 1.3.0... DEBUG: options are {[:out, :err]=>["/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks/compile.log", "a"]}
ERROR, review '/var/folders/st/02jjnpwd1bz15gp_7m7fm1lr0000gs/T/d20211205-39241-mrjeks/compile.log' to see what happened. Last lines are:
````

Which indicates that make recognises it is in the arm environment correctly, but compile does not.

**Comment by opoudjis** [comment]
I've got one temp build of libemf2svg for the emf2svg working, but the other temp builds continue not to. Investigating why.

**Comment by ronaldtse** [comment]
This seems related to the local environment. That said it would be useful in the future to run CI on arm64.

**Comment by ronaldtse** [comment]
Closing now, @opoudjis 's problem is fixed.
