### ISSUE TITLE
Windows 2022 support

### ISSUE THREAD

**Issue by maxirmx** [metanorma/libemf2svg#21]
- Requires vcpkg update
- vcpkg update suffers from https://github.com/microsoft/vcpkg/issues/23448
However, sligtly outdated version works (@75ae1ef)
-  External project that we relied on has disappered   -- https://github.com/bigcat26/argp-standalone.git
We have to find another windows port

**Comment by ant1j** [comment]
Hello,
I am trying to build the library on windows but it seems vcpkg cannot download the right gzip file (for libiconv) because the versions asked is nowhere to be found in the many mirrors used to DL it.

Is there any way this can be done?
Thanks

**Comment by ronaldtse** [comment]
@ant1j thanks for the report! I've moved the issue to #39 , where @maxirmx will investigate. Thanks!
