### ISSUE TITLE
Add build for Alpine Linux

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/libemf2svg#27]

**Comment by ronaldtse** [comment]
Thank you @maxirmx !

**Comment by maxirmx** [comment]
Alpine linux build that we have does not work for https://github.com/metanorma/packed-mn/issues/158
It depends on shared versions of libpng, freetype and fontconfig.   These three libraries  are included in Ubuntu basic configuration. However, on Alpine they are not a part of minimal configuration.  Probably libemf2svg needs to be statically linked against libpng, freetype and fontconfig

**Comment by ronaldtse** [comment]
@maxirmx it seems that it is possible to statically link those dependencies. Could you please help implement this? Thanks!
