### ISSUE TITLE
Switch on wrong fill_mode

### ISSUE THREAD

**Issue by KeterSCP** [metanorma/libemf2svg#38]
I've noticed at least 2 places where switch over `states->currentDeviceContext.fill_mode` is compared to wrong enum.

First:
https://github.com/metanorma/libemf2svg/blob/792609a1d0591a741e3e882fdd053eb8bf619590/src/lib/emf2svg_print.c#L45-L58

Second:
https://github.com/metanorma/libemf2svg/blob/792609a1d0591a741e3e882fdd053eb8bf619590/src/lib/emf2svg_utils.c#L296-L306

Here values are compared to `PolygonFillMode`, but `states->currentDeviceContext.fill_mode` is a brush style. Probably those switches should be done over `states->currentDeviceContext.fill_polymode`

**Comment by maxirmx** [comment]
Thank you, @KeterSCP 
Do you have an example which is affected by this issue ?

**Comment by KeterSCP** [comment]
Hi @maxirmx, thanks for the response! Unfortunately, I cannot share example file due to the company's NDA

**Comment by maxirmx** [comment]
> Hi @maxirmx, thanks for the response! Unfortunately, I cannot share example file due to the company's NDA

Ok, let me ask it in a better way - can you advise how it needs to be fixed ?
Thank you

**Comment by KeterSCP** [comment]
@maxirmx Sure! As mentioned in the issue description a fix would be to change

```diff
- switch (states->currentDeviceContext.fill_mode) {
+ switch (states->currentDeviceContext.fill_polymode) {
```
